import { createHash } from "node:crypto";
import type { Screen, ScreenListQuery } from "@snapcrawl/shared";
import type { ScreenDoc } from "../../models/screen";
import { escapeRegex } from "../projects/service";

// Capture helpers (FR-BE-040/041). Pure key-building/filter/serialization so they
// are unit-testable without S3 or a DB.

/** The content types FR-BE-040 allows a capture to be, and their extensions. */
const KEY_EXTENSIONS: Record<string, string> = { "image/webp": "webp", "image/png": "png" };

/**
 * Server-generated object key for a screenshot. The extension never chooses it
 * (FR-BE-040 — "a server-generated key"), and `isServerIssuedKey` below is what
 * makes that true rather than merely intended.
 *
 * The fingerprint is HASHED, not sanitised. The previous derivation stripped
 * every character outside `[A-Za-z0-9_-]` and fell back to the literal `state`
 * if nothing survived — which is not injective, and silently so: `a/b` and `ab`
 * produced one key, and every all-punctuation fingerprint produced
 * `state.png`. Distinct states would then overwrite each other's bytes in S3
 * while keeping separate DB rows (the unique index is on the RAW fingerprint),
 * so the gallery would show one screenshot under two entries and nothing
 * anywhere would report an error. A digest is injective for any input the
 * extension can produce, and needs no escaping to be path-safe.
 *
 * Existing screens are unaffected: `s3Key` is stored per row and read from
 * there, so this only governs keys minted from here on.
 */
export function screenKey(sessionId: string, fingerprint: string, contentType: string): string {
  const ext = KEY_EXTENSIONS[contentType] ?? "png";
  const digest = createHash("sha256").update(fingerprint).digest("hex").slice(0, 32);
  return `sessions/${sessionId}/${digest}.${ext}`;
}

/**
 * Is `key` one this server would actually have issued for this session + state?
 *
 * `completeCapture` receives the key from the client, and a capture-scoped token
 * is the least-trusted credential in the system (C-05: the extension's code is
 * public, so its token is effectively public too). Unchecked, the holder could
 * name ANY object in the bucket: point a screen row at someone else's
 * screenshot and read it back through the signed GET on `GET /screens/:id`,
 * which presigns whatever `s3Key` says without a second thought. Cross-tenant
 * read, using only the endpoint's own documented inputs.
 *
 * This is an allowlist, not a sanitiser — it is generated by the same function
 * that mints keys, so the two cannot drift apart. `contentType` is absent from
 * the completion body, so both legal extensions are candidates; the set is
 * still exactly two strings, both fully determined by server-side state.
 */
export function candidateScreenKeys(sessionId: string, fingerprint: string): string[] {
  return Object.keys(KEY_EXTENSIONS).map((ct) => screenKey(sessionId, fingerprint, ct));
}

export function isServerIssuedKey(key: string, sessionId: string, fingerprint: string): boolean {
  return candidateScreenKeys(sessionId, fingerprint).includes(key);
}

/** GET /sessions/:id/screens Mongo filter: session-scoped + gallery filters
 *  (url substring, depth, duplicate) + cursor (FR-AP-040). */
export function screenListFilter(
  sessionId: string,
  opts: Pick<ScreenListQuery, "cursor" | "url" | "depth" | "duplicate" | "variant">,
): Record<string, unknown> {
  // FR-EX-090 — a run is ONE device, so a session holds one variant. Filter only
  // when the caller actually asks; unfiltered is the right default so a session
  // never looks empty just because the UI guessed the wrong tab.
  const filter: Record<string, unknown> = { sessionId };
  if (opts.variant === "mobile") filter.variant = "mobile";
  else if (opts.variant === "desktop") filter.variant = { $ne: "mobile" };
  if (opts.cursor) filter._id = { $lt: opts.cursor };
  if (opts.url && opts.url.trim()) filter.url = { $regex: escapeRegex(opts.url.trim()), $options: "i" };
  if (opts.depth !== undefined) filter.depth = opts.depth;
  if (opts.duplicate !== undefined) filter.isDuplicate = opts.duplicate;
  return filter;
}

type ScreenUrls = { imageUrl?: string | null; thumbUrl?: string | null };

/** Map a screen document to the shared `Screen` shape. Signed URLs are attached
 *  by the caller: `thumbUrl` on gallery list + detail, `imageUrl` on detail only. */
export function serializeScreen(s: ScreenDoc, urls?: ScreenUrls): Screen {
  const te = s.triggerElement;
  return {
    id: String(s._id),
    sessionId: String(s.sessionId),
    projectId: String(s.projectId),
    fingerprint: s.fingerprint,
    url: s.url,
    title: s.title ?? "",
    depth: s.depth ?? 0,
    parentScreenId: s.parentScreenId ? String(s.parentScreenId) : null,
    triggerElement: te
      ? { selector: te.selector ?? "", text: te.text ?? "", tag: te.tag ?? "", role: te.role ?? null }
      : null,
    contentHash: s.contentHash,
    width: s.width ?? null,
    height: s.height ?? null,
    fullPage: s.fullPage ?? false,
    variant: s.variant === "mobile" ? "mobile" : "desktop",
    mobileReflowed: s.mobileReflowed ?? null,
    isDuplicate: s.isDuplicate ?? false,
    capturedAt: s.capturedAt ?? null,
    createdAt: s.createdAt,
    imageUrl: urls?.imageUrl ?? undefined,
    thumbUrl: urls?.thumbUrl ?? undefined,
  };
}

/** Thumbnail object key for a screen (FR-BE-042). Falls back to the full-image
 *  key until real WebP thumbnails are generated. */
export function thumbKeyOf(s: Pick<ScreenDoc, "thumbKey" | "s3Key">): string {
  return s.thumbKey ?? s.s3Key;
}
